Goreleaser brew
padok-team/tfautomv pull request #12
Opened 2022-09-16 20:15 UTC by StanGirard

2022-09-16 22:04 UTC, busser requested changes
How can we test that this works well?

Also, should we add the tfautomv-maintainers team as maintainers to the new tap repository?

2022-09-16 22:04 UTC, busser commented on .gitignore
> +.envrc
I agree that this should be added to .gitignore 👍

However I think we can make the comment clearer:
```suggestion
# Local direnv configuration
.envrc
```

2022-09-17 20:00 UTC, StanGirard commented
@busser The issue is we can't. Just try it. If it fails, delete the last commits and release and retry. 

You need to have the github token in your env variables that is all.

2022-09-17 20:02 UTC, StanGirard commented
And yes tfautomv-maintainers should be added as maintainers or we could let anybody at Padok use it.

I'd go for the second option.

2022-09-22 09:35 UTC, merged